### ISSUE TITLE
Request to join this organization- SWOC'21

### ISSUE THREAD

**Issue by Kuhoo-Chandra** [openAOD/Python-PatternHouse#895]
Username: Kuhoo-Chandra
please assign me python symbolic patterns no 12 to 19.
@ASLManasa 
@aryashah2k

**Comment by ASLManasa** [comment]
ok assigning to you. try to Complete it within 3days

**Comment by aryashah2k** [comment]
Please use the join repository for request to join the org, I have sent you an invite and once you join the individual issues will be assigned by me or @ASLManasa
